### ISSUE TITLE
Crossing paths yield unexpected fill patterns - brush tool

### ISSUE THREAD

**Issue by jwzimmer-zz** [fsih/papergrapher#19]
Reported by @ericrosenbaum during Paint Editor Internal Playtest 7/6/17:
> crossing paths results in a weird fill pattern when drawing a closed shape with the brush tool 

Chrome, Mac OS

**Example**
<img width="86" alt="screen shot 2017-07-06 at 12 21 38 pm" src="https://user-images.githubusercontent.com/1320456/27929051-754bb516-625f-11e7-92d8-8bec3f37e9ef.png">

**Comment by fsih** [comment]
Dupe of https://github.com/fsih/papergrapher/issues/29
