### ISSUE TITLE
Hard to distinguish between a point and its 2 handles when selecting point on a curve

### ISSUE THREAD

**Issue by jwzimmer-zz** [fsih/papergrapher#28]
Reported by @seotts during Paint Editor Internal Playtest 7/6/17:
> It's hard to tell the difference between the point and its 2 "handles" when you select a point on the curve because they are the same color and almost the same size

Chrome, Mac OS, Scratch+

**Label:** scratch+

**Comment by fsih** [comment]
Let's make it so you can't click and drag handles that aren't visible, and make one of handles or manipulation points squares instead
