### ISSUE TITLE
How to re-color an existing brush stroke?

### ISSUE THREAD

**Issue by jwzimmer-zz** [fsih/papergrapher#58]
Reported by @ericrosenbaum during Paint Editor Internal Playtest 7/6/17:
> setting a color for fill or stroke to clear does not seem to work for an existing brush stroke

Chrome, Mac OS, Blobs+

**Label:** blobs+

**Comment by fsih** [comment]
Ok talked to eric and figured out the repro

You have to change the color to transparent, then click the canvas instead of clicking OK
