### ISSUE TITLE
Ungrouping changes layer order

### ISSUE THREAD

**Issue by jwzimmer-zz** [fsih/papergrapher#64]
Reported by @christanbalch & others during Paint Editor Internal Playtest 7/6/17:
> Ungrouping a layer changes the layer order; not sure if this is a bug, but it did confuse me when it happened - @christanbalch
> Grouping / Ungrouping cause the selected objects to jump to the top most layer - @carljbowman
> Erasing a line that connects (like an "o" shape) does nothing.  - @speakkvisually
> Ungrouping the unicorn's head caused the layer ordering to change. - @thisandagain

**Steps to Repro:**
> Select a set of shapes/path and group them - @christanbalch
> Import layered vector artwork, ungroup section - @speakkvisually
> Select a set of shapes/path and group them - @carljbowman

Chrome, Mac OS, Blobs+, Scratch+

**Label:** blobs+, scratch+

**Comment by fsih** [comment]
I drew a collection of five shapes, and tried to group them. One of the shapes "disappeared" because it went behind another shape that it had been in front of before grouping
- mres
