### ISSUE TITLE
Paint Editor - Design Pass 1

### ISSUE THREAD

**Issue by carljbowman** [fsih/papergrapher#86]
Tracking issue for the post-workshop design pass. If we are feeling good about all or a subset of the tools based on the workshop with kids, I will begin a pass on the paint editor UI for the GUI.

[To be fleshed out]

**Comment by fsih** [comment]
We should probably track this in https://github.com/LLK/scratch-paint/issues since I'm planning to mostly abandon this repo when we finish up with the prototype

**Comment by carljbowman** [comment]
Moved the issue.
